name: wordiest
description: 'A collection of word games'
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.25.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  husky: ^0.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/
